name: eoreader
channels:
  - conda-forge
dependencies:         # everything under this, installed by conda
  - python==3.7
  - pip
  - pip:                # everything under this, installed by pip
      - -r file:./requirements.txt